### ISSUE TITLE
[Bug] Results Pages and Rankings mismatch at the end

### ISSUE THREAD

**Issue by Jambrose777** [Cubing-at-Home/cubing-at-home#111]
Reproduce:
1. Go to: https://results.cubingathome.com/cah2.1/event/skewb-r1
2. Click Next until you reach the end (should be the 6th page as 523 results), So you are on this page:
![image](https://user-images.githubusercontent.com/11577241/109397957-a252cf00-7907-11eb-91fc-f50d8730ea24.png)
 
3. Click Back
So now you will be on the first page (Carter being ranked 1) but the rankings start with 501.
![image](https://user-images.githubusercontent.com/11577241/109397978-cd3d2300-7907-11eb-9ef6-3a325040da29.png)

Proposed solution:
Disable the next button when on the last page.

**Comment by louismeunier** [comment]
Technically part of the cubing-at-home-*results* repo, will work on it for next competition.

**Comment by louismeunier** [comment]
closed by https://github.com/Cubing-at-Home/cubing-at-home-results/pull/12
